use serde::Serialize;

#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ProviderCategory {
    Recommended,
    Advanced,
    Local,
    ComingSoon,
}

#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ProviderStatus {
    Available,
    ComingSoon,
}

#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ApiFormat {
    Anthropic,
    OpenAiCompatible,
    Ollama,
    Gemini,
    AcornCloud,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ProviderMetadata {
    pub id: &'static str,
    pub display_name: &'static str,
    pub category: ProviderCategory,
    pub api_format: ApiFormat,
    pub default_model: &'static str,
    pub available_models: &'static [&'static str],
    pub default_endpoint: &'static str,
    pub allow_custom_endpoint: bool,
    pub requires_api_key: bool,
    pub api_key_url: Option<&'static str>,
    pub featured: bool,
    pub status: ProviderStatus,
}

pub fn provider_catalog() -> Vec<ProviderMetadata> {
    vec![
        ProviderMetadata {
            id: "anthropic",
            display_name: "Anthropic Claude",
            category: ProviderCategory::Recommended,
            api_format: ApiFormat::Anthropic,
            default_model: "claude-haiku-4-5",
            available_models: &["claude-haiku-4-5", "claude-sonnet-4-5", "claude-opus-4-5"],
            default_endpoint: "https://api.anthropic.com/v1/messages",
            allow_custom_endpoint: true,
            requires_api_key: true,
            api_key_url: Some("https://console.anthropic.com/settings/keys"),
            featured: true,
            status: ProviderStatus::Available,
        },
        ProviderMetadata {
            id: "openai",
            display_name: "OpenAI",
            category: ProviderCategory::Recommended,
            api_format: ApiFormat::OpenAiCompatible,
            default_model: "gpt-5-mini",
            available_models: &["gpt-5-mini", "gpt-5", "gpt-5-nano", "gpt-4.1-mini"],
            default_endpoint: "https://api.openai.com/v1/chat/completions",
            allow_custom_endpoint: true,
            requires_api_key: true,
            api_key_url: Some("https://platform.openai.com/api-keys"),
            featured: false,
            status: ProviderStatus::Available,
        },
        ProviderMetadata {
            id: "deepseek",
            display_name: "DeepSeek",
            category: ProviderCategory::Recommended,
            api_format: ApiFormat::OpenAiCompatible,
            default_model: "deepseek-chat",
            available_models: &["deepseek-chat", "deepseek-reasoner"],
            default_endpoint: "https://api.deepseek.com/v1/chat/completions",
            allow_custom_endpoint: true,
            requires_api_key: true,
            api_key_url: Some("https://platform.deepseek.com/api_keys"),
            featured: true,
            status: ProviderStatus::Available,
        },
        ProviderMetadata {
            id: "openrouter",
            display_name: "OpenRouter",
            category: ProviderCategory::Recommended,
            api_format: ApiFormat::OpenAiCompatible,
            default_model: "anthropic/claude-haiku-4-5",
            available_models: &[
                "anthropic/claude-haiku-4-5",
                "anthropic/claude-sonnet-4-5",
                "openai/gpt-5-mini",
                "google/gemini-2.5-flash",
                "meta-llama/llama-3.3-70b-instruct",
            ],
            default_endpoint: "https://openrouter.ai/api/v1/chat/completions",
            allow_custom_endpoint: false,
            requires_api_key: true,
            api_key_url: Some("https://openrouter.ai/keys"),
            featured: false,
            status: ProviderStatus::Available,
        },
        ProviderMetadata {
            id: "ollama",
            display_name: "Ollama (local)",
            category: ProviderCategory::Local,
            api_format: ApiFormat::Ollama,
            default_model: "qwen2.5:7b",
            available_models: &["qwen2.5:7b", "llama3.2:3b", "gemma3:4b", "mistral:7b"],
            default_endpoint: "http://localhost:11434",
            allow_custom_endpoint: true,
            requires_api_key: false,
            api_key_url: None,
            featured: false,
            status: ProviderStatus::Available,
        },
        ProviderMetadata {
            id: "gemini",
            display_name: "Google Gemini",
            category: ProviderCategory::Advanced,
            api_format: ApiFormat::Gemini,
            default_model: "gemini-2.5-flash",
            available_models: &["gemini-2.5-flash", "gemini-2.5-pro"],
            default_endpoint: "https://generativelanguage.googleapis.com/v1beta",
            allow_custom_endpoint: false,
            requires_api_key: true,
            api_key_url: Some("https://aistudio.google.com/app/apikey"),
            featured: false,
            status: ProviderStatus::ComingSoon,
        },
        ProviderMetadata {
            id: "qwen",
            display_name: "通义千问",
            category: ProviderCategory::Advanced,
            api_format: ApiFormat::OpenAiCompatible,
            default_model: "qwen-plus",
            available_models: &["qwen-plus", "qwen-turbo", "qwen-max"],
            default_endpoint: "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions",
            allow_custom_endpoint: false,
            requires_api_key: true,
            api_key_url: Some("https://dashscope.console.aliyun.com/apiKey"),
            featured: false,
            status: ProviderStatus::Available,
        },
        ProviderMetadata {
            id: "moonshot",
            display_name: "Moonshot Kimi",
            category: ProviderCategory::Advanced,
            api_format: ApiFormat::OpenAiCompatible,
            default_model: "moonshot-v1-8k",
            available_models: &["moonshot-v1-8k", "moonshot-v1-32k", "moonshot-v1-128k"],
            default_endpoint: "https://api.moonshot.cn/v1/chat/completions",
            allow_custom_endpoint: false,
            requires_api_key: true,
            api_key_url: Some("https://platform.moonshot.cn/console/api-keys"),
            featured: false,
            status: ProviderStatus::Available,
        },
        ProviderMetadata {
            id: "groq",
            display_name: "Groq",
            category: ProviderCategory::Advanced,
            api_format: ApiFormat::OpenAiCompatible,
            default_model: "llama-3.3-70b-versatile",
            available_models: &[
                "llama-3.3-70b-versatile",
                "llama-3.1-8b-instant",
                "mixtral-8x7b-32768",
            ],
            default_endpoint: "https://api.groq.com/openai/v1/chat/completions",
            allow_custom_endpoint: false,
            requires_api_key: true,
            api_key_url: Some("https://console.groq.com/keys"),
            featured: false,
            status: ProviderStatus::Available,
        },
        ProviderMetadata {
            id: "xai",
            display_name: "xAI Grok",
            category: ProviderCategory::Advanced,
            api_format: ApiFormat::OpenAiCompatible,
            default_model: "grok-2",
            available_models: &["grok-2", "grok-2-mini"],
            default_endpoint: "https://api.x.ai/v1/chat/completions",
            allow_custom_endpoint: false,
            requires_api_key: true,
            api_key_url: Some("https://console.x.ai/"),
            featured: false,
            status: ProviderStatus::Available,
        },
        ProviderMetadata {
            id: "mistral",
            display_name: "Mistral",
            category: ProviderCategory::Advanced,
            api_format: ApiFormat::OpenAiCompatible,
            default_model: "mistral-large-latest",
            available_models: &["mistral-large-latest", "mistral-small-latest"],
            default_endpoint: "https://api.mistral.ai/v1/chat/completions",
            allow_custom_endpoint: false,
            requires_api_key: true,
            api_key_url: Some("https://console.mistral.ai/api-keys"),
            featured: false,
            status: ProviderStatus::Available,
        },
        ProviderMetadata {
            id: "acorn_cloud",
            display_name: "🌰 Acorn Cloud",
            category: ProviderCategory::ComingSoon,
            api_format: ApiFormat::AcornCloud,
            default_model: "auto",
            available_models: &["auto"],
            default_endpoint: "https://api.acorn.app/v1/decompose",
            allow_custom_endpoint: false,
            requires_api_key: false,
            api_key_url: None,
            featured: false,
            status: ProviderStatus::ComingSoon,
        },
    ]
}

pub fn find_metadata(id: &str) -> Option<ProviderMetadata> {
    provider_catalog().into_iter().find(|m| m.id == id)
}
